  - name: disabling the default nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install nodejs and mysql
    ansible.builtin.dnf:
      name: "{{item}}"
      state: installed
    loop:
    - nodejs
    - mysql
  
  
  - name: adding user
    ansible.builtin.user: 
      name: Expense

  - name: creating directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: downloading the backend file
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip


# file aready exists in the remote server 
  - name: unzip backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip # by deafult checks in ansible server 
      dest: /app
      remote_src: yes # this checks the file in remote server

  - name: install  npm dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy backend service
    ansible.builtin.template:
      src: backend.service.j2
      dest: /etc/systemd/system/backend.service

  
  - name: instal python dependencies
    ansible.builtin.pip: 
      name:
      - PyMySql # to connect mysql db from ansible
      - cryptography
      executable: pip3.9

  - name: importing data into my sql
    community.mysql.mysql_db:
      login_user: root
      login_password: "{{login_password}}"
      login_host: "{{login_host}}"
      target: /app/schema/backend.sql
      state: import
      name: all

  - name: demon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable bakend service
    ansible.builtin.service:
      name: backend
      state: started
      enabled: yes
  # - name: demon reload with command 
  #   ansible.builtin.command: systemctl daemon-reload
  # - name: start  bakend service with command
  #   ansible.builtin.command: systemctl start backend
  # - name: enable backend with service with command
  #   ansible.builtin.command: systemctl enable backend
