  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
    
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: downloading the backend file
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
  - name: unzip frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip # by deafult checks in ansible server 
      dest: /usr/share/nginx/html
      remote_src: yes # this checks the file in remote server
    
  - name: copy  expense.conf
    ansible.builtin.template:
      src: expense.conf.j2
      dest: /etc/nginx/default.d/expense.conf
    notify:
    - restart nginx

