- name: installing mysql-server 
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start sql server
  ansible.builtin.service:
    name: mysqld
    state: started 
    enabled: yes

- name: instal python dependencies
  ansible.builtin.pip: 
    name:
    - PyMySql
    - cryptography
    executable: pip3.9

  #check password already set up
- name: check db connection
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    filter: version
    ignore_errors: yes
    register: mysql_connection_output

- name: print result of mysql connection
  ansible.builtin.debug:
    msg: "output: {{mysql_connection_output}}"
      
- name: set up root password of mysql
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
  when: mysql_connection_output.failed is true